//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRIT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Contact
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string InquirySpecification { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<long> ContactNo { get; set; }
        public string InquiryText { get; set; }
    }
}
