//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRIT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Colleges
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Colleges()
        {
            this.tbl_Registration = new HashSet<tbl_Registration>();
        }
    
        public int collegeId { get; set; }
        public string registrationId { get; set; }
        public string collegeName { get; set; }
        public string Address { get; set; }
        public Nullable<long> contact1 { get; set; }
        public Nullable<long> contact2 { get; set; }
        public string website { get; set; }
        public string email { get; set; }
        public string TPOName { get; set; }
        public string PrincipalName { get; set; }
        public string Description { get; set; }
        public string Degree { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Registration> tbl_Registration { get; set; }
    }
}
