//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRIT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CandidateWithCourseDetails
    {
        public int CandidateId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string CandidateExperience { get; set; }
        public string Gender { get; set; }
        public string DateOfBirth { get; set; }
        public string EmailId { get; set; }
        public long MobileNo { get; set; }
        public Nullable<long> AltMobileNo { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string HighestEducation { get; set; }
        public string Specialization { get; set; }
        public string InstituteName { get; set; }
        public Nullable<short> YearOfPassing { get; set; }
        public string University { get; set; }
        public string PercentageOrGrade { get; set; }
        public short CourseNameId { get; set; }
        public short CourseTypeId { get; set; }
        public Nullable<short> HoursPerDay { get; set; }
        public Nullable<int> Fees { get; set; }
        public Nullable<short> Duration { get; set; }
        public Nullable<short> CourseCategory { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
