//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRIT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Employee()
        {
            this.tbl_EmploymentDetails = new HashSet<tbl_EmploymentDetails>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string DateofBirth { get; set; }
        public string EmailId { get; set; }
        public string Designation { get; set; }
        public long MobileNo { get; set; }
        public Nullable<long> AltMobileNo { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public long Pincode { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string HighestEducation { get; set; }
        public string Specialization { get; set; }
        public string InstituteName { get; set; }
        public int YearOfPassing { get; set; }
        public string University { get; set; }
        public string InstituteLocation { get; set; }
        public decimal Percentage { get; set; }
        public string EmployeeType { get; set; }
        public long AdharCardNo { get; set; }
        public string PassportNo { get; set; }
        public string PANNo { get; set; }
        public string BloodGroup { get; set; }
        public string BankName { get; set; }
        public Nullable<long> AccountNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EmploymentDetails> tbl_EmploymentDetails { get; set; }
    }
}
